apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-front
  template:
    metadata:
      labels:
        app: nginx-front
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
