@startuml deployment

footer 13.3
scale max 1024 width

skinparam nodesep 10
skinparam ranksep 40

!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!includeurl KubernetesPuml/kubernetes_Common.puml
!includeurl KubernetesPuml/kubernetes_Context.puml
!includeurl KubernetesPuml/kubernetes_Simplified.puml

!includeurl KubernetesPuml/OSS/KubernetesPod.puml
!includeurl KubernetesPuml/OSS/KubernetesSecret.puml
!includeurl KubernetesPuml/OSS/KubernetesCm.puml

Cluster_Boundary(cluster, "Kubernetes Cluster") {
  Namespace_Boundary(ns1, "Namespace1") {
    KubernetesPod(pod1, "pod\nnginx", "")
    KubernetesCm(cm1, "Config\nindex.html", "")
    KubernetesSecret(sec1, "Secret\nTLS cert", "")
    }

  pod1 <-- cm1
  pod1 <-- sec1

}

@enduml

@enduml
