@startuml pod-to-pod

footer 12.4
scale max 1024 width

skinparam nodesep 10
skinparam ranksep 40
skinparam actorStyle awesome

!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureSimplified.puml

!includeurl AzurePuml/Networking/AzureLoadBalancer.puml


!includeurl KubernetesPuml/kubernetes_Common.puml
!includeurl KubernetesPuml/kubernetes_Context.puml
!includeurl KubernetesPuml/kubernetes_Simplified.puml

!includeurl KubernetesPuml/OSS/KubernetesPod.puml
!includeurl KubernetesPuml/OSS/KubernetesDeploy.puml
!includeurl KubernetesPuml/OSS/KubernetesSvc.puml

left to right direction
actor User as user
Cluster_Boundary(cluster, "Cloud Provider"){
  AzureLoadBalancer(lb, "\nLoad\nBalancer", "")
  Cluster_Boundary(service_resizer, "Kubernetes Cluster") {
    KubernetesPod(pod_1, "pod-1\n10.244.1.11", "")
    KubernetesPod(pod_2, "pod-2\n10.244.2.12", "")
    KubernetesPod(pod_3, "pod-3\n10.244.3.13", "")
    KubernetesSvc(svc_main, "LoadBalancer\n\n10.128.1.10", "")

    svc_main --> pod_1
    svc_main --> pod_2
    svc_main --> pod_3
  }
}
user -[thickness=4,#green]--> lb
lb -[thickness=4,#green]--> svc_main: Трафик
@enduml
