apiVersion: v1
kind: Pod
metadata:
  name: multitool-pod
  labels:
    name: multitool-pod
spec:
  containers:
  - name: multitool
    image: praqma/network-multitool
    ports:
      - containerPort: 8080
