apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-mtool-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-mtool
  template:
    metadata:
      labels:
        app: nginx-mtool
    spec:
      containers:
        - name: multitool
          image: praqma/network-multitool
          env:
            - name: HTTP_PORT
              value: "1180"
            - name: HTTPS_PORT
              value: "11443"
          ports:
            - containerPort: 1180
              name: http-port
            - containerPort: 11443
              name: https-port
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
