apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logger
  labels:
    app: logger
spec:
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: varlog
              mountPath: /var/log/syslog
      volumes:
        - name: varlog
          hostPath:
            path: /var/log/syslog
