@startuml deployment

footer 12.3
scale max 1024 width

skinparam nodesep 10
skinparam ranksep 40

!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!includeurl KubernetesPuml/kubernetes_Common.puml
!includeurl KubernetesPuml/kubernetes_Context.puml
!includeurl KubernetesPuml/kubernetes_Simplified.puml

!includeurl KubernetesPuml/OSS/KubernetesPod.puml
!includeurl KubernetesPuml/OSS/KubernetesDeploy.puml
!includeurl KubernetesPuml/OSS/KubernetesRs.puml


Cluster_Boundary(cluster, "Kubernetes Cluster") {
  KubernetesDeploy(deploy, "deployment", "")

  Service_Boundary(v1, "v1") #LightBlue {
    KubernetesRs(rs1, "rs-1", "")
    KubernetesPod(pod1, "pod-1", "")
    KubernetesPod(pod2, "pod-2", "")
  }

  Service_Boundary(v2, "v2") #LightGreen {
    KubernetesRs(rs2, "rs-2", "")
    KubernetesPod(pod3, "pod-3", "")
    KubernetesPod(pod4, "pod-4", "")
  }


  deploy -d-> rs1
  deploy -d-> rs2
  rs1 --> pod1
  rs1 --> pod2
  rs2 --> pod3
  rs2 --> pod4
}


@enduml
