@startuml deployment

footer 13.2
scale max 1024 width

skinparam nodesep 10
skinparam ranksep 40

!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!includeurl KubernetesPuml/kubernetes_Common.puml
!includeurl KubernetesPuml/kubernetes_Context.puml
!includeurl KubernetesPuml/kubernetes_Simplified.puml

!includeurl KubernetesPuml/OSS/KubernetesPod.puml
!includeurl KubernetesPuml/OSS/KubernetesPv.puml

left to right direction

Cluster_Boundary(cluster, "Kubernetes Cluster") {
  KubernetesPv(pv, "Persistent Volume", " ")
  Node_Boundary(node1, "Node1") {
    Namespace_Boundary(ns1, "NS1") {
        KubernetesPod(pod1, "pod-1", "")
    }
  }
  Node_Boundary(node2, "Node2") {
    Namespace_Boundary(ns2, "NS2") {
        KubernetesPod(pod2, "pod-2", "")
    }
    Namespace_Boundary(ns1, "NS1") {
        KubernetesPod(pod3, "pod-3", "")
    }
 }
  pv -u-> pod2
  pv -u-> pod1

}


@enduml
