@startuml deployment

footer 13.2
scale max 1024 width

skinparam nodesep 10
skinparam ranksep 40

!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!includeurl KubernetesPuml/kubernetes_Common.puml
!includeurl KubernetesPuml/kubernetes_Context.puml
!includeurl KubernetesPuml/kubernetes_Simplified.puml

!includeurl KubernetesPuml/OSS/KubernetesPod.puml
!includeurl KubernetesPuml/OSS/KubernetesPv.puml
!includeurl KubernetesPuml/OSS/KubernetesPvc.puml

left to right direction
Cluster_Boundary(cluster, "Kubernetes Cluster") {
  KubernetesPv(pv1, "PV1\n1GB:RWO", "")
  KubernetesPv(pv2, "PV2\n1GB:RWX", "")
  KubernetesPv(pv3, "PV3\n10GB:RWOP", "")

  Namespace_Boundary(ns1, "Namespace1") {
    KubernetesPod(pod1, "pod", "")
    KubernetesPvc(pvc1, "PVC\n1GB:RWO", "")
    }

  pod1 --> pvc1
  pvc1 --> pv1
  pvc1 -[#white]- pv2
  pvc1 -[#white]- pv3
}

@enduml

@enduml
